export const PASSWORD_MIN_LENGTH = 6;

export const PASSWORD_REGEX = `.{${PASSWORD_MIN_LENGTH}}`;

export const EMAIL_INVALID = 'EMAIL_INVALID';
export const EMAIL_NOT_UNIQUE = 'EMAIL_NOT_UNIQUE';
export const EMAIL_REQUIRED = 'EMAIL_REQUIRED';
export const NAME_REQUIRED = 'NAME_REQUIRED';
export const NAME_NOT_UNIQUE = 'NAME_NOT_UNIQUE';
export const PASSWORD_REQUIRED = 'PASSWORD_REQUIRED';
export const PASSWORD_INVALID = 'PASSWORD_INVALID';
export const CONFIRM_PASSWORD_REQUIRED = 'CONFIRM_PASSWORD_REQUIRED';
export const PASSWORDS_NOT_EQUAL = 'PASSWORDS_NOT_EQUAL';
export const CONNECTION_FAILED = 'CONNECTION_FAILED';
